renta_autos/renta_autos/Controllers/DetallesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using renta_autos.Models;
using Rotativa;

namespace renta_autos.Controllers
{
    public class DetallesController : Controller
    {
        // GET: Detalles
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult CreateUpdate(int Id_alquiler = 0, Vehiculos v= null)
        {

            if(v != null)
            {
                ViewBag.vehiculo = v;
            }

            if (Id_alquiler > 0)
            {
                using (var context = new Contextoss())
                {
                    var data = context.Alquileres.Where(x => x.Id_alquiler == Id_alquiler).FirstOrDefault();
                    return View(data);

                }
            }
            else
            {
                Alquiler alquiler = new Alquiler();
                return View(alquiler);
            }
        }


        [HttpPost]
        public ActionResult CreateUpdate(Alquiler alquiler)
        {
            if (ModelState.IsValid)
            {
                //alquiler.Total = ()

                var Nuevo = alquiler.Id_alquiler == 0 ? true : false;

                if (Nuevo)
                {
                    using (var context = new Contextoss())
                    {
                        context.Alquileres.Add(alquiler);
                        context.SaveChanges();
                    }
                }
                else
                {
                    using (var context = new Contextoss())
                    {
                        var data = context.Alquileres.Where(x => x.Id_alquiler == alquiler.Id_alquiler).FirstOrDefault();
                        data.Cliente = alquiler.Cliente;
                        data.Telefono = alquiler.Telefono;
                        data.Dui = alquiler.Dui;
                        data.Fecha_inicio = alquiler.Fecha_inicio;
                        data.Fecha_fin = alquiler.Fecha_fin;
                        data.Total = alquiler.Total;


                        context.SaveChanges();
                    }

                }

                return View("Enviados");
            }
            else
            {
                return View(alquiler);
            }
        }


        public ActionResult MostrarDetalle()
        {
            using (var context = new Contextoss())
            {
                var data = context.Alquileres.ToList();
                ViewBag.datos = data;

                return View();
            }
        }

        public ActionResult Imprimir()
        {
            using (var context = new Contextoss())
            {
                var data = context.Alquileres.ToList();
                ViewBag.datos = data;
            }

            return new ViewAsPdf("PDF")
            {
                PageSize = Rotativa.Options.Size.A4,
                PageMargins = new Rotativa.Options.Margins(10, 20, 10, 20),
                FileName = "Factura.pdf"
            };
        }

        public ActionResult Alquilar(int Id_vehiculo) {

            using (var context = new Contextoss())
            {
              
                var data = context.Vehiculos.Where(x => x.Id_vehiculo == Id_vehiculo).FirstOrDefault();
                data.Estado = false;
                return RedirectToAction("CreateUpdate", data);

            }
        }
    }

}

renta_autos/renta_autos/Controllers/MarcaController.cs
using renta_autos.Models;
using Rotativa;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace renta_autos.Controllers
{
    public class MarcaController : Controller
    {
        // GET: Marca
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CreateOrUpdateMarca(int Id = 0)
        {
            if (Id > 0)
            {
                using (var context = new Contextoss())
                {
                    var data = context.Marcas.Where(x => x.Id_marca == Id).FirstOrDefault();
                    return View(data);
                }
            }
            else
            {
                Marcas model = new Marcas();
                return View(model);
            }


        }
        [HttpPost]
        public ActionResult CreateOrUpdateMarca(Marcas model)
        {

            if (ModelState.IsValid)
            {

                var IsNew = model.Id_marca == 0 ? true : false;

                if (IsNew)
                {
                    using (var context = new Contextoss())
                    {
                        context.Marcas.Add(model);
                        context.SaveChanges();
                        ViewBag.IsNew = IsNew;
                        Thread.Sleep(2000);
                        return RedirectToAction("CreateOrUpdateMarca");
                    }
                }
                else
                {
                    using (var context = new Contextoss())
                    {
                        var data = context.Marcas.Where(x => x.Id_marca == model.Id_marca).FirstOrDefault();

                        data.Marca = model.Marca;
                        context.SaveChanges();
                        ViewBag.IsNew = IsNew;
                        Thread.Sleep(2000);
                        return RedirectToAction("MostrarDatos");
                    }
                }


                // Marcas m = new Marcas()

            }
            else
            {
                return View(model);
            }



        }

        public ActionResult MostrarDatos()
        {

            using (var context = new Contextoss())
            {
                var data = context.Marcas.ToList();
                ViewBag.datos = data;

                return View();
            }
        }
        public ActionResult DeleteMarca(int id_marca)
        {
            using (var context = new Contextoss())
            {
                var data = context.Marcas.Where(x => x.Id_marca == id_marca).FirstOrDefault();

                context.Marcas.Remove(data);
                context.SaveChanges();
            }
            Thread.Sleep(1000);
            return RedirectToAction("MostrarDatos");
        }





    }
}

renta_autos/renta_autos/Controllers/ModeloController.cs
using renta_autos.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace renta_autos.Controllers
{
    public class ModeloController : Controller
    {
        // GET: Modelo
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult CreateOrUpdateModelos(int Id = 0)
        {
            if (Id > 0)
            {
                using (var context = new Contextoss())
                {
                    var data = context.Modelos.Where(x => x.Id_modelo == Id).FirstOrDefault();
                    return View(data);
                }
            }
            else
            {
                Modelos model = new Modelos();
                return View(model);
            }


        }
        [HttpPost]
        public ActionResult CreateOrUpdateModelos(Modelos model)
        {

            if (ModelState.IsValid)
            {

                var IsNew = model.Id_modelo == 0 ? true : false;

                if (IsNew)
                {
                    using (var context = new Contextoss())
                    {
                        context.Modelos.Add(model);
                        context.SaveChanges();
                        ViewBag.IsNew = IsNew;
                        Thread.Sleep(2000);
                        return RedirectToAction("CreateOrUpdateModelo");
                    }
                }
                else
                {
                    using (var context = new Contextoss())
                    {
                        var data = context.Modelos.Where(x => x.Id_modelo == model.Id_modelo).FirstOrDefault();

                        data.Modelo = model.Modelo;
                        context.SaveChanges();
                        ViewBag.IsNew = IsNew;
                        Thread.Sleep(2000);
                        return RedirectToAction("MostrarDatos");
                    }
                }

                

               
            }
            else
            {
                return View(model);
            }



        }

        public ActionResult MostrarDatos()
        {
            
            using (var context = new Contextoss())
            {
                var data = context.Modelos.ToList();
                ViewBag.datos = data;

                return View();
            }
        }
        public ActionResult DeleteModelo(int Id_modelo)
        {
            using (var context = new Contextoss())
            {
                var data = context.Modelos.Where(x => x.Id_modelo == Id_modelo).FirstOrDefault();

                context.Modelos.Remove(data);
                context.SaveChanges();
            }
            Thread.Sleep(1000);
            return RedirectToAction("MostrarDatos");
        }





    }
}
    

renta_autos/renta_autos/Controllers/VehiculosController.cs
using renta_autos.Models;
using Rotativa;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace renta_autos.Controllers
{
    public class VehiculosController : Controller
    {
        // GET: Vehiculos
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult MostrarDatos()
        {
           
            using (var context = new Contextoss())
            {
                var data = context.Vehiculos.ToList();
                ViewBag.datos = data;

                return View();
            }
        }

        public ActionResult CreateOrUpdateVehiculo(int Id_vehiculo = 0)
        {
            if (Id_vehiculo > 0)
            {
                using (var context = new Contextoss())
                {
                    var data = context.Vehiculos.Where(x => x.Id_vehiculo == Id_vehiculo).FirstOrDefault();
                    return View(data);
                }
            }
            else
            {
                Vehiculos model = new Vehiculos();
                return View(model);
            }
        }

        [HttpPost]
        public ActionResult CreateOrUpdateVehiculo(Vehiculos model)
        {

            if (ModelState.IsValid)
            {
                //model.Promedio = (model.Nota1 + model.Nota2 + model.Nota3) / 3;
                //model.Estado = model.Promedio >= 6 ? "Aprobado" : "Reprobado";

                var IsNew = model.Id_vehiculo == 0 ? true : false;

                if (IsNew)
                {
                    using (var context = new Contextoss())
                    {
                        context.Vehiculos.Add(model);
                        context.SaveChanges();
                        ViewBag.IsNew = IsNew;
                        Thread.Sleep(2000);
                        return RedirectToAction("CreateOrUpdateVehiculo");
                    }
                }
                else
                {
                    using (var context = new Contextoss())
                    {
                        var data = context.Vehiculos.Where(x => x.Id_vehiculo == model.Id_vehiculo).FirstOrDefault();

                        data.Placa = model.Placa;
                        data.Anio = model.Anio;
                        data.Transmision = model.Transmision;
                        data.Precio_hora = model.Precio_hora;
                        data.Estado = model.Estado;
                        data.Id_marca = model.Id_marca;
                        data.Id_modelo = model.Id_modelo;
                        data.Id_tipo_vehiculo = model.Id_tipo_vehiculo;

                        context.SaveChanges();
                        ViewBag.IsNew = IsNew;
                        Thread.Sleep(2000);
                        return RedirectToAction("MostrarDatos");
                    }
                }
              
            }
            else
            {
                return View(model);
            }

        }

        public ActionResult DeleteVehiculo(int Id_vehiculo)
        {
            using (var context = new Contextoss())
            {
                var data = context.Vehiculos.Where(x => x.Id_vehiculo == Id_vehiculo).FirstOrDefault();

                context.Vehiculos.Remove(data);
                context.SaveChanges();
            }
            Thread.Sleep(1000);
            return RedirectToAction("MostrarDatos");
        }

        public ActionResult ImprimirPDF()
        {
            using (var context = new Contextoss())
            {
                var data = context.Vehiculos.ToList();

                ViewBag.datos = data;
            }

            return new ViewAsPdf("IndexPdf")
            {
                PageSize = Rotativa.Options.Size.A4,
                PageMargins = new Rotativa.Options.Margins(10, 20, 10, 20),
                FileName = "ListadoVehiculos.pdf"
            };
        }




    }
}

renta_autos/renta_autos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Rentacar</title>

    <!-- Bootstrap core CSS -->
    <link href="~/startbootstrap-shop-homepage-gh-pages/startbootstrap-shop-homepage-gh-pages/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">


    <!-- Custom styles for this template -->
    <link href="~/startbootstrap-shop-homepage-gh-pages/startbootstrap-shop-homepage-gh-pages/css/shop-homepage.css" rel="stylesheet">
    <style>

        .dropdown-item:hover {
            background-color: blue;
            color: white;

        }
        #Table {
            margin: auto;
        }
    </style>
    <link rel="stylesheet" href="sweetalert2.min.css">

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" @Html.ActionLink("Rentacar", "Index", "Home")></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" @Html.ActionLink("Inicio", "Index", "Home")

                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Mantenimiento
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" @Html.ActionLink("Marcas", "MostrarDatos", "Marca")</a>
                            <a class="dropdown-item " @Html.ActionLink("Modelos", "MostrarDatos", "Modelo")</a>
                            <a class="dropdown-item" @Html.ActionLink("Tipo de vehículos", "MostrarDatos", "Tipo_Vehiculos")</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" @Html.ActionLink("Vehículos", "MostrarDatos", "Vehiculos")</a>
                        </div>

                    </li>
                    @*<li class="nav-item">
                            <a class="nav-link" href="#">Alquiler</a>
                        </li>*@
                    <li class="nav-item">
                        <a class="nav-link" @Html.ActionLink("Detalle de alquiler", "MostrarDetalle", "Detalles")</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div>
        @RenderBody()
        <hr />
        <footer class="py-5 bg-dark">
            <div class="container">
                <p class="m-0 text-center text-white">Copyright &copy;RentaCar CASS 2021</p>
            </div>
            <!-- /.container -->
        </footer>
    </div>

    <!-- Bootstrap core JavaScript -->
    <script src="~/startbootstrap-shop-homepage-gh-pages/startbootstrap-shop-homepage-gh-pages/vendor/jquery/jquery.min.js"></script>
    <script src="~/startbootstrap-shop-homepage-gh-pages/startbootstrap-shop-homepage-gh-pages/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@10"></script>



</body>

</html>