renta_autos/renta_autos/Models/TipoVehiculos.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace renta_autos.Models
{
    public class TipoVehiculos
    {
        [Key]
        public int Id_tipo_vehiculo { get; set; }

        [Required(ErrorMessage = "El tipo de vehículo es requerido")]
        public string Tipo_vehiculo { get; set; }

        //Llave foranea para la tabla de Vehiculos
        [ForeignKey("Id_tipo_vehiculo")]
        public ICollection<Vehiculos> Vehiculos { get; set; }
    }
}

renta_autos/renta_autos/Controllers/Tipo_VehiculosController.cs
using renta_autos.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace renta_autos.Controllers
{
    public class Tipo_VehiculosController : Controller
    {
        // GET: Tipo_Vehiculos
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult CreateOrUpdateTipo(int Id = 0)
        {
            if (Id > 0)
            {
                using (var context = new Contextoss())
                {
                    var data = context.TipoVehiculos.Where(x => x.Id_tipo_vehiculo == Id).FirstOrDefault();
                    return View(data);
                }
            }
            else
            {
                TipoVehiculos model = new TipoVehiculos();
                return View(model);
            }


        }
        [HttpPost]
        public ActionResult CreateOrUpdateTipo(TipoVehiculos model)
        {

            if (ModelState.IsValid)
            {

                var IsNew = model.Id_tipo_vehiculo == 0 ? true : false;

                if (IsNew)
                {
                    using (var context = new Contextoss())
                    {
                        context.TipoVehiculos.Add(model);
                        context.SaveChanges();
                        ViewBag.IsNew = IsNew;
                        Thread.Sleep(2000);
                        return RedirectToAction("CreateOrUpdateTipo");
                    }
                }
                else
                {
                    using (var context = new Contextoss())
                    {
                        var data = context.TipoVehiculos.Where(x => x.Id_tipo_vehiculo == model.Id_tipo_vehiculo).FirstOrDefault();

                        data.Tipo_vehiculo = model.Tipo_vehiculo;
                        context.SaveChanges();
                        ViewBag.IsNew = IsNew;
                        Thread.Sleep(2000);
                        return RedirectToAction("MostrarDatos");
                    }
                }

               

                
            }
            else
            {
                return View(model);
            }



        }

        public ActionResult MostrarDatos()
        {
           
            using (var context = new Contextoss())
            {
                var data = context.TipoVehiculos.ToList();
                ViewBag.datos = data;

                return View();
            }
        }
        public ActionResult DeleteTipo(int Id_tipo_vehiculo)
        {
            using (var context = new Contextoss())
            {
                var data = context.TipoVehiculos.Where(x => x.Id_tipo_vehiculo == Id_tipo_vehiculo).FirstOrDefault();

                context.TipoVehiculos.Remove(data);
                context.SaveChanges();
            }
            Thread.Sleep(1000);
            return RedirectToAction("MostrarDatos");
        }





    }
}

renta_autos/renta_autos/Views/Tipo_Vehiculos/Correcto.cshtml
@{
    ViewBag.Title = "Correcto";
}

<br />


@if (ViewBag.IsNew == true)
{
    <h2 style="color:deepskyblue;text-align:center">
        ¡Datos agregados correctamente!
    </h2>
}
else
{
    <h2 style="color:deepskyblue;text-align:center">
        ¡Datos actualizados correctamente!
    </h2>
}

renta_autos/renta_autos/Views/Tipo_Vehiculos/CreateOrUpdateTipo.cshtml
@model renta_autos.Models.TipoVehiculos
@using renta_autos.Models;
@{
    ViewBag.Title = "CreateOrUpdateTipo";
}

<br />
<center>
    @if (Model.Id_tipo_vehiculo > 0)
    {
        <h1>Editar Tipos Vehiculos</h1>
    }
    else
    {
        <h1>Agregar Tipos Vehiculos</h1>
    }
</center>
<br />

@using (Html.BeginForm("CreateOrUpdateTipo", "Tipo_Vehiculos", FormMethod.Post))
{
    @Html.HiddenFor(x => x.Id_tipo_vehiculo)

    <table>
        <tr>
            <td><label>Tipo Vehiculo :</label></td>
            <td>
                @Html.TextBoxFor(x => x.Tipo_vehiculo, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.Tipo_vehiculo, null, new { @class = "text-danger" })
            </td>
        </tr>

        <tr>
            <td colspan="2">
                <center>
                    <input type="submit" class="btn btn-success" onclick="setTimeout('CreateUpdate(@Model.Id_tipo_vehiculo)',1000);" value="Enviar Datos" />
                </center>
            </td>
        </tr>
    </table>
}
<script>
    function CreateUpdate(id) {
        if (id > 0) {
            Swal.fire({
                position: 'center',
                icon: 'info',
                title: '¡Editado!',
                showConfirmButton: true,
                timer: 2000
            })
        } else {
            Swal.fire({
                position: 'center',
                icon: 'success',
                title: 'Dato Registrado',
                showConfirmButton: false,
                timer: 2000
            })
        }

    }

</script>

renta_autos/renta_autos/Views/Tipo_Vehiculos/MostrarDatos.cshtml
@using renta_autos.Models
@{
    ViewBag.Title = "MostrarDatos";
    List<TipoVehiculos> lista = ViewBag.datos != null ? ViewBag.datos : new List<TipoVehiculos>();
}

<br />
<center>
    <h2>Listado de Tipos de Vehiculos</h2>
    <a class="btn btn-outline-primary" @Html.ActionLink("Agregar", "CreateOrUpdateTipo", "Tipo_Vehiculos")</a>
</center>
<br />
<br />
<br />
<br />

<div class="container">
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
            <table class="table table-striped ">
                <thead>
                    <tr>

                        <th>Id</th>
                        <th>Tipo</th>
                        <th></th>
                        <th></th>

                    </tr>
                </thead>
                <tbody>
                    @if (lista.Count() > 0)
                    {
                        foreach (var a in lista)
                        {
                            <tr>

                                <td>@a.Id_tipo_vehiculo</td>
                                <td>@a.Tipo_vehiculo</td>

                                <td>
                                    @Html.ActionLink("Editar", "CreateOrUpdateTipo", "Tipo_Vehiculos", new { id = a.Id_tipo_vehiculo }, new { @class = "btn btn-success" })
                                </td>
                                <td>
                                    <button type="button" onclick="ObtenerId(@a.Id_tipo_vehiculo)" class="btn btn-danger" data-toggle="modal" data-target="#EliminarModel">
                                        Eliminar
                                    </button>
                                    @*@Html.ActionLink("Eliminar", "DeleteAlumno", "Alumno", new { id_alumno = a.id }, new { @class = "btn btn-danger" })*@
                                </td>
                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="10">
                                <center>
                                    <b>¡No hay resultados para mostrar!</b>
                                </center>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>






<!-- Modal -->
<div class="modal fade" id="EliminarModel" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">

                <h5 class="modal-title" id="exampleModalLabel"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <center>
                    ¿DESEA ELIMINAR EL REGISTRO?
                    <input type="hidden" id="id_oculto" />
                </center>
            </div>
            <div class="modal-footer">
                <CENTER>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                    <button type="button" onclick="EliminarRegistro()" class="btn btn-danger">Si</button>
                </CENTER>
            </div>
        </div>
    </div>
</div>





<script>
    function ObtenerId(valor) {

        $("#id_oculto").val(valor);
    }
    function EliminarRegistro() {
        var id = $("#id_oculto").val();
        var id = $("#id_oculto").val();
        Swal.fire({
            position: 'center',
            icon: 'error',
            title: 'Dato eliminado',
            showConfirmButton: false,
            timer: 1500
        })
        window.location.href = "/Tipo_Vehiculos/DeleteTipo?Id_tipo_vehiculo=" + id;
    }
</script>